In [ ]:
import pandas as pd

Leemos los archivos

In [ ]:
Int_movil = pd.read_csv(r'data\Ingresos_Internet_Movil.csv')
Int_fijo = pd.read_csv(r'data\Ingresos_Internet_Fijo.csv')

Aplicamos Data Cleansing

In [53]:
#Int_movil['Ingresos (miles de $)'] = Int_movil['Ingresos (miles de $)'].str.replace('[.$ ]','', regex=True)
Int_movil['Periodo'] = Int_movil['Periodo'].str.replace('\s+|\d{4}', '', regex=True)
Int_movil['Ingresos (miles de $)'] = Int_movil['Ingresos (miles de $)'].astype(int)

Int_fijo['Ingresos (miles de pesos)'] = Int_fijo['Ingresos (miles de pesos)'].str.replace('.','')
Int_fijo['Periodo'] = Int_fijo['Periodo'].str.replace('\s+|\d{4}', '', regex=True)

Guardamos los nuevos csv

In [ ]:
Int_movil.to_csv('data\Ingresos_Internet_Movil_CD.csv', index=False)
Int_fijo.to_csv('data\Ingresos_Internet_Fijo_CD.csv', index=False)

In [55]:
# Leer los archivos CSV en DataFrames
df_ingresos = Int_movil
df_inflacion = pd.read_csv(r'data\df_inflacion.csv')

# Extraer el valor de la inflación trimestral
inflacion_trimestral = df_inflacion['Inflacion trimestral'].dropna().iloc[-1]

# Multiplicar la columna "Ingresos (miles de $)" por la inflación trimestral
df_ingresos['Ingresos (miles de $)'] *= inflacion_trimestral

# Guardar el resultado en un nuevo archivo CSV
df_ingresos.to_csv('archivo_ingresos_actualizado.csv', index=False)

In [58]:
df1 = pd.read_csv('archivo_ingresos_actualizado.csv')
df1.round(2)

     Año  Trimestre  Ingresos (miles de $)   Periodo
0   2013          1          -3.717405e+10   Ene-Mar
1   2013          2           2.954126e+10   Abr-Jun
2   2013          3          -7.744329e+09  Jul-Sept
3   2013          4          -3.717405e+10   Oct-Dic
4   2014          1          -9.027387e+09   Ene-Mar
5   2014          2          -2.116339e+10   Abr-Jun
6   2014          3          -3.717405e+10  Jul-Sept
7   2014          4           2.131087e+10   Oct-Dic
8   2015          1          -3.051699e+09   Ene-Mar
9   2015          2          -3.717405e+10   Abr-Jun
10  2015          3          -3.278893e+10  Jul-Sept
11  2015          4          -2.782310e+10   Oct-Dic
12  2016          1          -3.717405e+10   Ene-Mar
13  2016          2          -1.350098e+10   Abr-Jun
14  2016          3           9.910214e+08  Jul-Sept
15  2016          4          -3.717405e+10   Oct-Dic
16  2017          1           3.558676e+10   Ene-Mar
17  2017          2           0.000000e+00   Abr-Jun
18  2017          3          -3.717405e+10  Jul-Sept
19  2017          4           1.775320e+10   Oct-Dic
20  2018          1          -1.005176e+10   Ene-Mar
21  2018          2          -3.717405e+10   Abr-Jun
22  2018          3           1.705815e+10  Jul-Sept
23  2018          4           3.297850e+10   Oct-Dic
24  2019          1          -3.717405e+10   Ene-Mar
25  2019          2           0.000000e+00   Abr-Jun
26  2019          3           2.720266e+09  Jul-Sept
27  2019          4          -3.717405e+10   Oct-Dic
28  2020          1          -1.205505e+10   Ene-Mar
29  2020          2           0.000000e+00   Abr-Jun
30  2020          3          -3.717405e+10  Jul-Sept
31  2020          4          -2.292885e+09   Oct-Dic
32  2021          1          -2.911146e+10   Ene-Mar
33  2021          2          -3.717405e+10   Abr-Jun
34  2021          3          -1.232842e+10  Jul-Sept
35  2021          4           3.707096e+10   Oct-Dic
36  2022          1          -3.717405e+10   Ene-Mar
37  2022          2           2.902554e+10   Abr-Jun
38  2022          3           2.290819e+10  Jul-Sept